### ISSUE TITLE
stuck when using signinRedirect()

### ISSUE THREAD

**Issue by LeToyek** [zhazhazhu/vue3-oidc#3]
when I turn on my auto auth in create Oidc, it can run the auth normaly, but when I'm trying to turn it off and using manual auth with signinRedirect(), It can navigate to the login page but can not navigate back to my dashboard page. It stuck after I press login on the login page
```
the url that I stucked on
http://localhost:5173/oidc-callback?code=<the code>
```

**Comment by zhazhazhu** [comment]
I suggest you manually redirect on the callback page
