### ISSUE TITLE
连续刷新token

### ISSUE THREAD

**Issue by zfy171** [zhazhazhu/vue3-oidc#7]
token过期自动刷新时 会偶发连续请求多次的问题

**Comment by zhazhazhu** [comment]
请给我一个最小复现链接

**Comment by zfy171** [comment]
已解决 问题是因为我在配置项中添加 automaticSilentRenew: true 属性导致

**Comment by zhazhazhu** [comment]
> 已解决 问题是因为我在配置项中添加 automaticSilentRenew: true 属性导致

好的
